package docs

import (
	"os"
	"path/filepath"
	"strings"
)

// GuidePage renders one written document as a page of the site. The Markdown is the only copy;
// this is a rendering of it, regenerated by `make docs` and held to a no-diff check, so the two
// cannot say different things.
func GuidePage(repoRoot string, g *Guide, guides []Guide) ([]byte, []error) {
	source := filepath.Join(repoRoot, filepath.FromSlash(g.Source))
	raw, err := os.ReadFile(source) //nolint:gosec // a path Guides() derived from the repository tree
	if err != nil {
		return nil, []error{err}
	}
	body, errs := Markdown(g.Source, string(raw), Site{
		Published: PublishedMap(guides),
		Exists: func(repoPath string) bool {
			_, err := os.Stat(filepath.Join(repoRoot, filepath.FromSlash(repoPath)))
			return err == nil
		},
	})
	if len(errs) > 0 {
		return nil, prefix(g.Source, errs)
	}
	return renderPage(&pageSpec{
		Title:       g.Title,
		Description: describe(string(raw)),
		URL:         g.URL,
		Current:     g.URL,
		Body:        body,
		Guides:      guides,
	}), nil
}

func prefix(source string, errs []error) []error {
	out := make([]error, 0, len(errs))
	for _, err := range errs {
		out = append(out, &sourceError{source: source, err: err})
	}
	return out
}

type sourceError struct {
	source string
	err    error
}

func (e *sourceError) Error() string { return e.source + " " + e.err.Error() }
func (e *sourceError) Unwrap() error { return e.err }

// describe takes the page's own first sentence of prose as its meta description, so a shared
// link says what the page is without anyone maintaining a second summary of it.
func describe(doc string) string {
	for line := range strings.Lines(doc) {
		line = strings.TrimSpace(line)
		switch {
		case line == "", strings.HasPrefix(line, "#"), strings.HasPrefix(line, "*Part of"),
			strings.HasPrefix(line, ">"), strings.HasPrefix(line, "|"), strings.HasPrefix(line, "-"):
			continue
		}
		return summarize(line)
	}
	return "Documentation for assaio."
}

// summarize strips the inline Markdown a meta tag cannot render and cuts to one sentence.
func summarize(line string) string {
	line = strings.NewReplacer("`", "", "**", "", "*", "", "_", "").Replace(line)
	for _, end := range []string{". ", " — ", ": "} {
		if at := strings.Index(line, end); at > 60 {
			return line[:at+1]
		}
	}
	if len(line) > 200 {
		if cut := strings.LastIndex(line[:200], " "); cut > 0 {
			return line[:cut] + "…"
		}
	}
	return line
}
