package docs

import "strings"

// HTML renders the reference as one self-contained page. It is generated and committed as
// site/reference.html, which is why it names no version: a served file may not carry a stamp
// that has to be updated at every tag (docs/site.md), and the schema version belongs in the
// JSON, where a tool reads it. Every URL below drops the ".html": Cloudflare Workers Assets
// serves the file at /reference and 307s the extension away, so a canonical naming the file
// would point at a redirect.
func HTML(ref *Reference) []byte {
	var b strings.Builder
	b.WriteString(head)
	b.WriteString(`<body><div class="wrap">`)
	writeHeader(&b)
	writeSignals(&b, ref.Signals)
	writeSources(&b, ref.Sources)
	writeValidators(&b, ref.Validators)
	writeCommands(&b, ref.Commands, ref.GlobalFlags)
	writeConfig(&b, ref.Config)
	writeWire(&b, ref.ValidatorInput, ref.MetricWire)
	b.WriteString(footer)
	b.WriteString(`</div>` + themeScript + `</body></html>` + "\n")
	return []byte(b.String())
}

// themeScript adopts the choice the main page stored. Without it a reader who set dark there
// lands on a light page, because the two files share a palette but not a document. There is no
// toggle here on purpose: one control, on the page that has one.
const themeScript = `<script>
try{var t=localStorage.getItem('assaio-theme'); if(t) document.documentElement.setAttribute('data-theme',t);}catch(e){}
</script>`

const head = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>assaio reference — every signal, source, validator, command and setting</title>
<meta name="description" content="The enumerable surfaces of assaio, generated from the binary's own registries: the signal catalog, the source-depth matrix, the metric validators, the command tree, the configuration keys and the metric-plugin protocol.">
<link rel="canonical" href="https://assaio.dev/reference">
<meta property="og:type" content="website">
<meta property="og:url" content="https://assaio.dev/reference">
<meta property="og:title" content="assaio reference">
<meta property="og:description" content="Every signal, source, validator, command and setting — generated from the binary, not transcribed.">
<meta property="og:image" content="https://assaio.dev/og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="assaio — measure whether AI coding spend is delivering">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="https://assaio.dev/og.png">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%233E8B79'/%3E%3Cpath d='M9 22 16 10l7 12' stroke='%23EFEAE1' stroke-width='2.4' fill='none' stroke-linejoin='round'/%3E%3C/svg%3E">
<style>` + pageStyle + `</style>
</head>
`

func writeHeader(b *strings.Builder) {
	b.WriteString(`<header>
<h1>assaio reference</h1>
<p class="lede">Everything assaio can enumerate about itself, read from the registries inside the
binary rather than transcribed by hand. What a figure <em>means</em> is prose and lives in the
docs; what can be listed is listed here, and a check fails the build when this page and the
binary disagree.</p>
<nav>
<a href="/">← assaio.dev</a>
<a href="#signals">Signals</a>
<a href="#sources">Sources</a>
<a href="#validators">Validators</a>
<a href="#commands">Commands</a>
<a href="#config">Configuration</a>
<a href="#metric-plugin">Metric plugin</a>
<a href="https://github.com/assaio/assaio/releases">Releases</a>
</nav>
</header>`)
}

const footer = `<footer>
<p>Generated by <code>assaio-agent docs export --format html</code>. This page names no release:
which version is current is stated once, on the
<a href="https://github.com/assaio/assaio/releases">releases page</a>, where it cannot fall behind.
It loads nothing — no fonts, no analytics, no third-party requests.</p>
</footer>`
